version: "3.7"

services:
    mysql:
        image: mysql
        restart: always
        ports:
            - ${DEV_HOST_PORT_MYSQL}:3306
        volumes:
            # diretórios
            - mysql_data:/var/lib/mysql
            # arquivos
            - ./services/mysql/default.cnf:/etc/mysql/conf.d/default.cnf:ro
        env_file:
            # docker
            - .env
            # aplicação
            - ../../.env.local

    nginx:
        image: nginx:alpine
        restart: always
        depends_on:
            - php
        ports:
            - ${DEV_HOST_PORT_HTTP}:80
        volumes:
            # diretórios
            - ../..:/var/www/dev
            # arquivos
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf.template:ro
        command: >
            /bin/sh -c
            "envsubst '$$APP_BASE_URL'
            < /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"
        env_file:
            # docker
            - .env
            # aplicação
            - ../../.env.local

    php:
        image: ${DEV_DOCKER_IMAGE_PHP}:dev
        build:
            context: .
            dockerfile: ../docker/dev/Dockerfile
            args:
                BASE_IMAGE: ${DEV_DOCKER_IMAGE_PHP}:base
        restart: always
        volumes:
            # diretórios
            - ../..:/var/www/dev
            - ${DEV_COMPOSER_DIR}:/composer
            # arquivos
            - ./services/php/php.ini-development:/usr/local/etc/php/php.ini:ro
            - ./services/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        working_dir: /var/www/dev
        env_file:
            # docker
            - .env
            # aplicação
            - ../../.env.local
        user: ${DEV_UID}:${DEV_GID}

volumes:
    mysql_data:
